<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>b027e55e-d650-466a-aae2-270d9ea0c04e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='td-header-search-top']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.td-search-form > #td-header-search-top</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7d31189-6be4-428b-b550-607fa04df393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpb_button wpb_btn-inverse btn</value>
      <webElementGuid>6655df7b-d4b5-4cd9-9127-4571d71e7c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5fe21423-92ff-403f-8cd6-0b9560ffcdd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td-header-search-top</value>
      <webElementGuid>a6626213-ddba-4116-94cc-57cb94d2f261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>81339171-13d0-448a-9d9b-f4956ad77b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search </value>
      <webElementGuid>0bc985c3-52f7-46c9-8123-867b8b1380e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td-outer-wrap&quot;)/div[@class=&quot;topbanner&quot;]/div[@class=&quot;td-container searchbanner&quot;]/div[1]/form[@class=&quot;td-search-form&quot;]/button[@id=&quot;td-header-search-top&quot;]</value>
      <webElementGuid>35897f25-ee56-4390-a6f1-93dc817ec3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Frame/Page_Selenium IFrame/iframe_iframe_a</value>
      <webElementGuid>6c4d02eb-173a-445f-8d84-7d0f5735e9f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='td-header-search-top']</value>
      <webElementGuid>2315ee8c-9585-4ae8-8817-fb97222e8f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='td-outer-wrap']/div[2]/div/div/form/button</value>
      <webElementGuid>074bc34e-e8cb-434d-a744-f0933d13ca61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9966bfd0-b610-436e-b09a-5e1a6782c4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'td-header-search-top' and (text() = ' Search ' or . = ' Search ')]</value>
      <webElementGuid>d17fe8a8-f027-4b83-a874-9ddf32fff89d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
