<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Frame</name>
   <tag></tag>
   <elementGuidId>6da12818-392d-412a-9da3-82bfadc6ee81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>(//input[@id='td-header-search'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='td-header-search'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Frame/Page_Selenium IFrame/Frame_in</value>
      <webElementGuid>47876fd1-1fb3-4012-8251-41e08cc330d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
