<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_iframe_a</name>
   <tag></tag>
   <elementGuidId>323fd3a7-79f9-44f3-a486-aa35cd3986e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='iframe_a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;iframe_a&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>43add785-ba8e-42be-8d58-c08426e475aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframe_a</value>
      <webElementGuid>56bf46f2-912d-48c8-9ee4-7a1feefafacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://freshersnow.com</value>
      <webElementGuid>5cc2220c-0f29-41e9-87d3-ae9a3a44760f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-body-9163515251344049321&quot;)/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>c015259e-75e6-408f-bc83-035141074c93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='iframe_a']</value>
      <webElementGuid>c997dd36-e74f-44c1-bfcd-9f564da7c59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-9163515251344049321']/div/div/div/div/iframe</value>
      <webElementGuid>90239e3c-b60f-4ec3-b485-c6633cc09579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3e773649-0881-470a-a066-100bd981773b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'iframe_a' and @src = 'https://freshersnow.com']</value>
      <webElementGuid>f759d3b7-cf67-4aa3-8fef-083f7c15a2c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
