<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_s</name>
   <tag></tag>
   <elementGuidId>3d313200-7e6d-4003-b3ea-12a142f0bc88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='td-header-search'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.td-search-form > #td-header-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2019f567-ae70-4022-9beb-63702a48acae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>query-input</value>
      <webElementGuid>ea1117d9-e50a-48de-8be3-6d507fb9d605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td-header-search</value>
      <webElementGuid>a2425bb6-a32a-4121-a8de-f2435a8ab188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18e0c87d-8f3b-4e81-9ec9-28908293f7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>535a0b7d-5072-45a1-972e-a2d285bae698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fe140dca-2582-4d0a-a179-04bb000dca04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td-outer-wrap&quot;)/div[@class=&quot;topbanner&quot;]/div[@class=&quot;td-container searchbanner&quot;]/div[1]/form[@class=&quot;td-search-form&quot;]/input[@id=&quot;td-header-search&quot;]</value>
      <webElementGuid>61fbfb5f-a70f-4339-b2ab-0bab66a6bddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Frame/Page_Selenium IFrame/iframe_iframe_a</value>
      <webElementGuid>2fd4a864-f174-4e80-9373-b596687784d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='td-header-search'])[2]</value>
      <webElementGuid>4767f6b0-569c-49cc-a607-dfd545d922be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='td-outer-wrap']/div[2]/div/div/form/input</value>
      <webElementGuid>87ba8378-4243-43ee-83a9-72b061430a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>2e940213-a101-4e83-a626-8db8664e33e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'td-header-search' and @type = 'text' and @name = 's']</value>
      <webElementGuid>bdc5dc6b-d0e8-4775-a1cb-e13c324ed63e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
