<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_Parent framehtml1body1</name>
   <tag></tag>
   <elementGuidId>dc6c3a14-a57d-4acd-af60-87ff058e29f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>7b9edece-14aa-4951-afa0-cb2f2efe0117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Parent frame/html[1]/body[1]</value>
      <webElementGuid>1eb5c712-c9c7-499c-9f7f-47720dc0305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>ca976cd7-cc19-4c8f-9bfc-ff21b2a36f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Nested Frame/Page_DEMOQA/iframeframe1</value>
      <webElementGuid>b1e2a631-7142-4ed6-96eb-604f23989df6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>6e143c88-c79f-4da6-84c4-14509a503569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'Parent frame/html[1]/body[1]' or . = 'Parent frame/html[1]/body[1]')]</value>
      <webElementGuid>0d62f439-25af-4901-bf0a-163829dc9015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
